# Generated by Django 2.1 on 2018-10-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('time', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('game_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('horse_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('male', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Jockey',
            fields=[
                ('jockey_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=200)),
            ],
        ),
    ]
